export const STICKER = {
  HI: 'CAACAgIAAxkBAAMEYs8wr7LgcpbVW59bmQZgYwfOQNoAAncNAAJw2vFLFamrZN5ICLkpBA',
  SAD: 'CAACAgIAAxkBAAMTYs8zJkwZq342U42-HGkwTfGO1sEAAkMRAALpFfBLTAoWHBPPczwpBA',
  SADNESS:
    'CAACAgIAAxkBAAONYs9JAlLtBHs4816_Cz_FLq4IzTMAAiQLAAIEv_FLFuD22fNmUL0pBA',
  IMPORTANT:
    'CAACAgIAAxkBAAMUYs8zVLXXZkJ2QxMpiSq4reEtNLAAAjwVAAK51ZlKk9ZstNXzYlApBA',
  SIT: 'CAACAgIAAxkBAAMcYs8-6mJvCJ3-pUUUfeFSpKvO-5oAAnARAAJel_FLfRvnp9VRbG0pBA',
  LAUGH:
    'CAACAgIAAxkBAAPkYs9O-Bb4cQABJxrajJvOMqI2lAPyAAIDDgACvOnxSw17Jb0p_hhzKQQ',
  DONT_WORRY:
    'CAACAgIAAxkBAAPnYs9P_bjfP-zCy___QHX1rDGWMeUAArYQAAIiDIhKmq5-VmHYcwABKQQ',
  OK: 'CAACAgIAAxkBAAPpYs9RtO0xD0Ql6DbSAQddfWedFWAAApwTAALTvohKLPobhctNHPcpBA',
  CHECKING:
    'CAACAgIAAxkBAAIBaGLPX1vjexGVQtYqLkHjYcIvyMc_AALPDgACHe7xS0WGDYeJRqVaKQQ',
  PANIC:
    'CAACAgIAAxkBAAIBc2LPY7xA7ULbAAF_YwUPwxZ6bANFFwAClA0AAprM-EsH1TZ4naneTikE',
  SHOCK:
    'CAACAgIAAxkBAAIB62LPbpLMCLFy_yYgVtKej-CKkVzeAAKRFgAC5m7BSpK-2GGkRs5xKQQ',
  DONT_UNDERSTAND:
    'CAACAgIAAxkBAAICXmLPeZk5RC9LblAG2u0whSkftJamAAIzFAACRWCQSsmtiWmbUzGaKQQ',
};

export const constants = {
  STICKER,
};
